### ISSUE TITLE
Activity completion isn't working

### ISSUE THREAD

**Issue by TYNarita** [amandadoughty/moodle-mod_peerwork#21] opened 2024-04-09 12:54 UTC
Hello, this plugin is in use at University of Warwick and we are on Moodle version 4.1.8. 
We've just noticed that it doesn't work correctly with activity completion in that if you set completion criteria and the first student completes, it then shows the 'Done: [completion criteria]' label for all other students, regardless of whether they have completed it or not. However, if you go into the activity completion report under the 'Reports' tab, you'll be able to see there that they have not completed the activity.

**Comment by amandadoughty** [comment] 2024-11-09 13:19
Clsoing as duplicate of #13

**Closed by amandadoughty** 2024-11-09 13:19 UTC
